name: Test on Deploy to Main

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s tests -p "test_*.py"
          coverage report
          coverage xml

      - name: Generate coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true 
          format: markdown
          hide_complexity: true

      - name: Update README with coverage
        run: |
          coverage_percent=$(coverage report | grep TOTAL | awk '{print $4}')
          markdown_badge="![Coverage: $coverage_percent](https://img.shields.io/badge/Coverage-$coverage_percent-green?$(date +%s))"
          sed -i "s|<!-- COVERAGE_BADGE -->|$markdown_badge|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with coverage badge"
          git push
